WIDTH = 1200
HEIGHT = 720

BOTTOMROW_XY = (200, 100)

TOPROW_Y = 20

CARD_DIM = (98, 140)

CARD_SPACING = 20

CARD_SUITS = ["HEARTS", "DIAMONDS", "CLUBS", "SPADES"]

CARD_HOLDER_VER_OFFSET = 30

CARD_SMALL_ITEM_SIZE = (18, 21)

MOUSEHOLDER_OFFSET = (0, CARD_HOLDER_VER_OFFSET)
TOPLEFTHOLDER_OFFSET = (30, 0)
TOPRIGHTHOLDER_OFFSET = (0, 0)
BOTTOMROWHOLDER_OFFSET = (0, CARD_HOLDER_VER_OFFSET)


RESTART_BUTTON_SIZE = (50, 50)